// AUTO-GENERATED from supabase/migrations by lib/test/db-typegen.ts. Do not edit by hand.
// Refresh: npm run db:types   (CI fails when this file is stale: supabase/tests/db-types.test.ts)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type GeneratedDatabase = {
  public: {
    Tables: {
      analytics_events: {
        Row: {
          id: string;
          workspace_id: string;
          flow_id: string | null;
          contact_id: string | null;
          event_type: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          flow_id?: string | null;
          contact_id?: string | null;
          event_type: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          flow_id?: string | null;
          contact_id?: string | null;
          event_type?: string;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      artifacts: {
        Row: {
          id: string;
          workspace_id: string;
          kind: string;
          object_key: string;
          file_name: string;
          content_type: string;
          size_bytes: number;
          sha256: string;
          status: string;
          retention_until: string | null;
          campaign_id: string | null;
          task_id: string | null;
          execution_record_id: string | null;
          metadata: Json;
          created_by: string | null;
          created_by_worker: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          kind: string;
          object_key: string;
          file_name?: string;
          content_type: string;
          size_bytes: number;
          sha256: string;
          status?: string;
          retention_until?: string | null;
          campaign_id?: string | null;
          task_id?: string | null;
          execution_record_id?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_by_worker?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          kind?: string;
          object_key?: string;
          file_name?: string;
          content_type?: string;
          size_bytes?: number;
          sha256?: string;
          status?: string;
          retention_until?: string | null;
          campaign_id?: string | null;
          task_id?: string | null;
          execution_record_id?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_by_worker?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          deleted_at?: string | null;
        };
      };
      broadcast_recipients: {
        Row: {
          id: string;
          broadcast_id: string;
          contact_id: string;
          channel_id: string;
          status: string;
          sent_at: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          broadcast_id: string;
          contact_id: string;
          channel_id: string;
          status?: string;
          sent_at?: string | null;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          broadcast_id?: string;
          contact_id?: string;
          channel_id?: string;
          status?: string;
          sent_at?: string | null;
          error_message?: string | null;
        };
      };
      broadcasts: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          status: string;
          message_content: Json;
          segment_filter: Json | null;
          scheduled_for: string | null;
          total_recipients: number;
          sent: number;
          delivered: number;
          failed: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          status?: string;
          message_content?: Json;
          segment_filter?: Json | null;
          scheduled_for?: string | null;
          total_recipients?: number;
          sent?: number;
          delivered?: number;
          failed?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          status?: string;
          message_content?: Json;
          segment_filter?: Json | null;
          scheduled_for?: string | null;
          total_recipients?: number;
          sent?: number;
          delivered?: number;
          failed?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      browser_sessions: {
        Row: {
          id: string;
          workspace_id: string;
          platform: string;
          label: string;
          account_hint: string | null;
          status: string;
          storage_state_secret_id: string | null;
          credential_secret_id: string | null;
          capabilities: Json;
          permitted_use_confirmed: boolean;
          permitted_use_confirmed_by: string | null;
          permitted_use_confirmed_at: string | null;
          profile_key: string;
          expires_at: string | null;
          last_verified_at: string | null;
          last_error: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          allow_experimental: boolean;
          last_check_task_id: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          platform: string;
          label: string;
          account_hint?: string | null;
          status?: string;
          storage_state_secret_id?: string | null;
          credential_secret_id?: string | null;
          capabilities?: Json;
          permitted_use_confirmed?: boolean;
          permitted_use_confirmed_by?: string | null;
          permitted_use_confirmed_at?: string | null;
          profile_key?: string;
          expires_at?: string | null;
          last_verified_at?: string | null;
          last_error?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          allow_experimental?: boolean;
          last_check_task_id?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          platform?: string;
          label?: string;
          account_hint?: string | null;
          status?: string;
          storage_state_secret_id?: string | null;
          credential_secret_id?: string | null;
          capabilities?: Json;
          permitted_use_confirmed?: boolean;
          permitted_use_confirmed_by?: string | null;
          permitted_use_confirmed_at?: string | null;
          profile_key?: string;
          expires_at?: string | null;
          last_verified_at?: string | null;
          last_error?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          allow_experimental?: boolean;
          last_check_task_id?: string | null;
        };
      };
      campaigns: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          objective: string;
          status: string;
          owner_id: string | null;
          audience: Json;
          channel_ids: string[];
          voice: string;
          content_plan: Json;
          utm_defaults: Json;
          starts_at: string | null;
          ends_at: string | null;
          timezone: string;
          requires_approval: boolean;
          results: Json;
          notes: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          objective?: string;
          status?: string;
          owner_id?: string | null;
          audience?: Json;
          channel_ids?: string[];
          voice?: string;
          content_plan?: Json;
          utm_defaults?: Json;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string;
          requires_approval?: boolean;
          results?: Json;
          notes?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          objective?: string;
          status?: string;
          owner_id?: string | null;
          audience?: Json;
          channel_ids?: string[];
          voice?: string;
          content_plan?: Json;
          utm_defaults?: Json;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string;
          requires_approval?: boolean;
          results?: Json;
          notes?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
      };
      canned_replies: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          body: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          body: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          body?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      channels: {
        Row: {
          id: string;
          workspace_id: string;
          platform: string;
          late_account_id: string;
          username: string | null;
          display_name: string | null;
          profile_picture: string | null;
          webhook_id: string | null;
          webhook_secret: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_comment_cursor: string | null;
          comment_rules: Json | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          platform: string;
          late_account_id: string;
          username?: string | null;
          display_name?: string | null;
          profile_picture?: string | null;
          webhook_id?: string | null;
          webhook_secret?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_comment_cursor?: string | null;
          comment_rules?: Json | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          platform?: string;
          late_account_id?: string;
          username?: string | null;
          display_name?: string | null;
          profile_picture?: string | null;
          webhook_id?: string | null;
          webhook_secret?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_comment_cursor?: string | null;
          comment_rules?: Json | null;
        };
      };
      comment_logs: {
        Row: {
          id: string;
          channel_id: string;
          workspace_id: string;
          post_id: string | null;
          platform_comment_id: string;
          author_id: string | null;
          author_name: string | null;
          author_username: string | null;
          comment_text: string;
          matched_trigger_id: string | null;
          dm_sent: boolean;
          reply_sent: boolean;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          channel_id: string;
          workspace_id: string;
          post_id?: string | null;
          platform_comment_id: string;
          author_id?: string | null;
          author_name?: string | null;
          author_username?: string | null;
          comment_text: string;
          matched_trigger_id?: string | null;
          dm_sent?: boolean;
          reply_sent?: boolean;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          channel_id?: string;
          workspace_id?: string;
          post_id?: string | null;
          platform_comment_id?: string;
          author_id?: string | null;
          author_name?: string | null;
          author_username?: string | null;
          comment_text?: string;
          matched_trigger_id?: string | null;
          dm_sent?: boolean;
          reply_sent?: boolean;
          error?: string | null;
          created_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          domain: string;
          description: string;
          owner_id: string | null;
          lifecycle: string;
          source: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          domain?: string;
          description?: string;
          owner_id?: string | null;
          lifecycle?: string;
          source?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          domain?: string;
          description?: string;
          owner_id?: string | null;
          lifecycle?: string;
          source?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      contact_channels: {
        Row: {
          id: string;
          contact_id: string;
          channel_id: string;
          platform_sender_id: string;
          platform_username: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          contact_id: string;
          channel_id: string;
          platform_sender_id: string;
          platform_username?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          contact_id?: string;
          channel_id?: string;
          platform_sender_id?: string;
          platform_username?: string | null;
          created_at?: string;
        };
      };
      contact_custom_fields: {
        Row: {
          contact_id: string;
          field_id: string;
          value: string;
          updated_at: string;
        };
        Insert: {
          contact_id: string;
          field_id: string;
          value: string;
          updated_at?: string;
        };
        Update: {
          contact_id?: string;
          field_id?: string;
          value?: string;
          updated_at?: string;
        };
      };
      contact_tags: {
        Row: {
          contact_id: string;
          tag_id: string;
          created_at: string;
        };
        Insert: {
          contact_id: string;
          tag_id: string;
          created_at?: string;
        };
        Update: {
          contact_id?: string;
          tag_id?: string;
          created_at?: string;
        };
      };
      contact_touchpoints: {
        Row: {
          id: string;
          workspace_id: string;
          contact_id: string;
          campaign_id: string | null;
          variant_id: string | null;
          channel_id: string | null;
          source: string;
          utm: Json;
          external_ref: string | null;
          landing_url: string | null;
          note: string;
          dedupe_key: string | null;
          occurred_at: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          contact_id: string;
          campaign_id?: string | null;
          variant_id?: string | null;
          channel_id?: string | null;
          source: string;
          utm?: Json;
          external_ref?: string | null;
          landing_url?: string | null;
          note?: string;
          dedupe_key?: string | null;
          occurred_at?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          contact_id?: string;
          campaign_id?: string | null;
          variant_id?: string | null;
          channel_id?: string | null;
          source?: string;
          utm?: Json;
          external_ref?: string | null;
          landing_url?: string | null;
          note?: string;
          dedupe_key?: string | null;
          occurred_at?: string;
          created_by?: string | null;
          created_at?: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          workspace_id: string;
          display_name: string | null;
          email: string | null;
          avatar_url: string | null;
          is_subscribed: boolean;
          last_interaction_at: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          first_touch_source: string;
          first_touch_at: string | null;
          last_touch_at: string | null;
          first_campaign_id: string | null;
          last_campaign_id: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          display_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          is_subscribed?: boolean;
          last_interaction_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          first_touch_source?: string;
          first_touch_at?: string | null;
          last_touch_at?: string | null;
          first_campaign_id?: string | null;
          last_campaign_id?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          display_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          is_subscribed?: boolean;
          last_interaction_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          first_touch_source?: string;
          first_touch_at?: string | null;
          last_touch_at?: string | null;
          first_campaign_id?: string | null;
          last_campaign_id?: string | null;
        };
      };
      conversations: {
        Row: {
          id: string;
          workspace_id: string;
          channel_id: string;
          contact_id: string;
          late_conversation_id: string | null;
          platform: string;
          status: string;
          assigned_to: string | null;
          last_message_at: string | null;
          last_message_preview: string | null;
          unread_count: number;
          is_automation_paused: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          channel_id: string;
          contact_id: string;
          late_conversation_id?: string | null;
          platform: string;
          status?: string;
          assigned_to?: string | null;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          unread_count?: number;
          is_automation_paused?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          channel_id?: string;
          contact_id?: string;
          late_conversation_id?: string | null;
          platform?: string;
          status?: string;
          assigned_to?: string | null;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          unread_count?: number;
          is_automation_paused?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      custom_field_definitions: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          slug: string;
          type: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          slug: string;
          type?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          slug?: string;
          type?: string;
          created_at?: string;
        };
      };
      customer_notes: {
        Row: {
          id: string;
          workspace_id: string;
          company_id: string | null;
          contact_id: string | null;
          deal_id: string | null;
          body: string;
          author_id: string;
          created_at: string;
          work_item_id: string | null;
          conversation_id: string | null;
          mention_ids: string[];
        };
        Insert: {
          id?: string;
          workspace_id: string;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          body: string;
          author_id?: string;
          created_at?: string;
          work_item_id?: string | null;
          conversation_id?: string | null;
          mention_ids?: string[];
        };
        Update: {
          id?: string;
          workspace_id?: string;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          body?: string;
          author_id?: string;
          created_at?: string;
          work_item_id?: string | null;
          conversation_id?: string | null;
          mention_ids?: string[];
        };
      };
      customer_profiles: {
        Row: {
          id: string;
          workspace_id: string;
          contact_id: string;
          company_id: string | null;
          owner_id: string | null;
          lifecycle: string;
          source: string;
          lead_score: number;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          contact_id: string;
          company_id?: string | null;
          owner_id?: string | null;
          lifecycle?: string;
          source?: string;
          lead_score?: number;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          contact_id?: string;
          company_id?: string | null;
          owner_id?: string | null;
          lifecycle?: string;
          source?: string;
          lead_score?: number;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      deals: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string;
          company_id: string | null;
          contact_id: string | null;
          owner_id: string | null;
          stage: string;
          value_minor: number;
          currency: string;
          expected_close_at: string | null;
          closed_at: string | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string;
          company_id?: string | null;
          contact_id?: string | null;
          owner_id?: string | null;
          stage?: string;
          value_minor?: number;
          currency?: string;
          expected_close_at?: string | null;
          closed_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string;
          company_id?: string | null;
          contact_id?: string | null;
          owner_id?: string | null;
          stage?: string;
          value_minor?: number;
          currency?: string;
          expected_close_at?: string | null;
          closed_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      editorial_drafts: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          body: string;
          campaign: string;
          state: string;
          scheduled_at: string | null;
          timezone: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          version: number;
          created_at: string;
          updated_at: string;
          campaign_id: string | null;
          kind: string;
          link_url: string | null;
          utm: Json;
          asset_ids: string[];
          created_by: string | null;
          source_draft_id: string | null;
          source_task_id: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          body?: string;
          campaign?: string;
          state?: string;
          scheduled_at?: string | null;
          timezone?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
          campaign_id?: string | null;
          kind?: string;
          link_url?: string | null;
          utm?: Json;
          asset_ids?: string[];
          created_by?: string | null;
          source_draft_id?: string | null;
          source_task_id?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          body?: string;
          campaign?: string;
          state?: string;
          scheduled_at?: string | null;
          timezone?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
          campaign_id?: string | null;
          kind?: string;
          link_url?: string | null;
          utm?: Json;
          asset_ids?: string[];
          created_by?: string | null;
          source_draft_id?: string | null;
          source_task_id?: string | null;
        };
      };
      editorial_variants: {
        Row: {
          id: string;
          workspace_id: string;
          draft_id: string;
          channel_id: string;
          body: string;
          media_refs: string[];
          version: number;
          created_at: string;
          updated_at: string;
          publish_state: string;
          scheduled_at: string | null;
          execution_mode: string | null;
          idempotency_key: string | null;
          task_id: string | null;
          external_ref: string | null;
          external_url: string | null;
          published_at: string | null;
          last_error: string | null;
          attempt_count: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          draft_id: string;
          channel_id: string;
          body: string;
          media_refs?: string[];
          version?: number;
          created_at?: string;
          updated_at?: string;
          publish_state?: string;
          scheduled_at?: string | null;
          execution_mode?: string | null;
          idempotency_key?: string | null;
          task_id?: string | null;
          external_ref?: string | null;
          external_url?: string | null;
          published_at?: string | null;
          last_error?: string | null;
          attempt_count?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          draft_id?: string;
          channel_id?: string;
          body?: string;
          media_refs?: string[];
          version?: number;
          created_at?: string;
          updated_at?: string;
          publish_state?: string;
          scheduled_at?: string | null;
          execution_mode?: string | null;
          idempotency_key?: string | null;
          task_id?: string | null;
          external_ref?: string | null;
          external_url?: string | null;
          published_at?: string | null;
          last_error?: string | null;
          attempt_count?: number;
        };
      };
      execution_records: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string | null;
          correlation_id: string;
          provider: string;
          account_ref: string | null;
          operation: string;
          mode: string;
          attempt: number;
          status: string;
          started_at: string;
          finished_at: string | null;
          latency_ms: number | null;
          result_meta: Json;
          error_class: string | null;
          error_message: string | null;
          retry_decision: string;
          artifact_ids: string[];
          external_ref: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id?: string | null;
          correlation_id: string;
          provider: string;
          account_ref?: string | null;
          operation: string;
          mode: string;
          attempt?: number;
          status?: string;
          started_at?: string;
          finished_at?: string | null;
          latency_ms?: number | null;
          result_meta?: Json;
          error_class?: string | null;
          error_message?: string | null;
          retry_decision?: string;
          artifact_ids?: string[];
          external_ref?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string | null;
          correlation_id?: string;
          provider?: string;
          account_ref?: string | null;
          operation?: string;
          mode?: string;
          attempt?: number;
          status?: string;
          started_at?: string;
          finished_at?: string | null;
          latency_ms?: number | null;
          result_meta?: Json;
          error_class?: string | null;
          error_message?: string | null;
          retry_decision?: string;
          artifact_ids?: string[];
          external_ref?: string | null;
        };
      };
      flow_sessions: {
        Row: {
          id: string;
          contact_id: string;
          flow_id: string;
          channel_id: string;
          status: string;
          current_node_id: string | null;
          variables: Json;
          flow_stack: Json;
          waiting_until: string | null;
          waiting_for_input: boolean;
          human_takeover_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          contact_id: string;
          flow_id: string;
          channel_id: string;
          status?: string;
          current_node_id?: string | null;
          variables?: Json;
          flow_stack?: Json;
          waiting_until?: string | null;
          waiting_for_input?: boolean;
          human_takeover_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          contact_id?: string;
          flow_id?: string;
          channel_id?: string;
          status?: string;
          current_node_id?: string | null;
          variables?: Json;
          flow_stack?: Json;
          waiting_until?: string | null;
          waiting_for_input?: boolean;
          human_takeover_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      flow_versions: {
        Row: {
          id: string;
          flow_id: string;
          version: number;
          nodes: Json;
          edges: Json;
          viewport: Json | null;
          name: string;
          published_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          flow_id: string;
          version: number;
          nodes: Json;
          edges: Json;
          viewport?: Json | null;
          name: string;
          published_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          flow_id?: string;
          version?: number;
          nodes?: Json;
          edges?: Json;
          viewport?: Json | null;
          name?: string;
          published_by?: string | null;
          created_at?: string;
        };
      };
      flows: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          status: string;
          nodes: Json;
          edges: Json;
          viewport: Json | null;
          version: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          status?: string;
          nodes?: Json;
          edges?: Json;
          viewport?: Json | null;
          version?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          status?: string;
          nodes?: Json;
          edges?: Json;
          viewport?: Json | null;
          version?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gateway_workspace_bindings: {
        Row: {
          gateway_workspace_ref: string;
          workspace_id: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          gateway_workspace_ref: string;
          workspace_id: string;
          created_by?: string;
          created_at?: string;
        };
        Update: {
          gateway_workspace_ref?: string;
          workspace_id?: string;
          created_by?: string;
          created_at?: string;
        };
      };
      knowledge_sources: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          source_ref: string;
          enabled: boolean;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          source_ref: string;
          enabled?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          source_ref?: string;
          enabled?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      lead_intake_tokens: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          token_hash: string;
          default_campaign_id: string | null;
          created_by: string | null;
          created_at: string;
          last_used_at: string | null;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          token_hash: string;
          default_campaign_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          last_used_at?: string | null;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          token_hash?: string;
          default_campaign_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          last_used_at?: string | null;
          revoked_at?: string | null;
        };
      };
      legacy_queue_routes: {
        Row: {
          job_type: string;
          target: string;
          note: string | null;
          updated_at: string;
        };
        Insert: {
          job_type: string;
          target?: string;
          note?: string | null;
          updated_at?: string;
        };
        Update: {
          job_type?: string;
          target?: string;
          note?: string | null;
          updated_at?: string;
        };
      };
      mailbox_identities: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          address: string;
          gateway_account_ref: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          address: string;
          gateway_account_ref?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          address?: string;
          gateway_account_ref?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          direction: string;
          text: string | null;
          attachments: Json | null;
          quick_reply_payload: string | null;
          postback_payload: string | null;
          callback_data: string | null;
          platform_message_id: string | null;
          sent_by_flow_id: string | null;
          sent_by_node_id: string | null;
          sent_by_user_id: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          direction: string;
          text?: string | null;
          attachments?: Json | null;
          quick_reply_payload?: string | null;
          postback_payload?: string | null;
          callback_data?: string | null;
          platform_message_id?: string | null;
          sent_by_flow_id?: string | null;
          sent_by_node_id?: string | null;
          sent_by_user_id?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          direction?: string;
          text?: string | null;
          attachments?: Json | null;
          quick_reply_payload?: string | null;
          postback_payload?: string | null;
          callback_data?: string | null;
          platform_message_id?: string | null;
          sent_by_flow_id?: string | null;
          sent_by_node_id?: string | null;
          sent_by_user_id?: string | null;
          status?: string;
          created_at?: string;
        };
      };
      operator_notifications: {
        Row: {
          id: string;
          workspace_id: string;
          recipient_id: string;
          title: string;
          kind: string;
          entity_type: string;
          entity_id: string;
          dedupe_key: string;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          recipient_id: string;
          title: string;
          kind: string;
          entity_type: string;
          entity_id: string;
          dedupe_key: string;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          recipient_id?: string;
          title?: string;
          kind?: string;
          entity_type?: string;
          entity_id?: string;
          dedupe_key?: string;
          created_at?: string;
          read_at?: string | null;
        };
      };
      product_activity: {
        Row: {
          id: string;
          workspace_id: string;
          entity_type: string;
          entity_id: string;
          actor_id: string | null;
          action: string;
          changes: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          entity_type: string;
          entity_id: string;
          actor_id?: string | null;
          action: string;
          changes?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          entity_type?: string;
          entity_id?: string;
          actor_id?: string | null;
          action?: string;
          changes?: Json;
          created_at?: string;
        };
      };
      publish_receipts: {
        Row: {
          id: string;
          workspace_id: string;
          variant_id: string;
          task_id: string | null;
          idempotency_key: string;
          attempt: number;
          mode: string;
          provider: string;
          status: string;
          operation_ref: string | null;
          external_ref: string | null;
          external_url: string | null;
          error_class: string | null;
          error_code: string | null;
          error_message: string | null;
          parts: Json;
          poll_count: number;
          created_at: string;
          updated_at: string;
          settled_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          variant_id: string;
          task_id?: string | null;
          idempotency_key: string;
          attempt: number;
          mode: string;
          provider: string;
          status: string;
          operation_ref?: string | null;
          external_ref?: string | null;
          external_url?: string | null;
          error_class?: string | null;
          error_code?: string | null;
          error_message?: string | null;
          parts?: Json;
          poll_count?: number;
          created_at?: string;
          updated_at?: string;
          settled_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          variant_id?: string;
          task_id?: string | null;
          idempotency_key?: string;
          attempt?: number;
          mode?: string;
          provider?: string;
          status?: string;
          operation_ref?: string | null;
          external_ref?: string | null;
          external_url?: string | null;
          error_class?: string | null;
          error_code?: string | null;
          error_message?: string | null;
          parts?: Json;
          poll_count?: number;
          created_at?: string;
          updated_at?: string;
          settled_at?: string | null;
        };
      };
      scheduled_jobs: {
        Row: {
          id: string;
          type: string;
          payload: Json;
          run_at: string;
          status: string;
          attempts: number;
          last_error: string | null;
          created_at: string;
          claimed_at: string | null;
          dedupe_key: string | null;
          workspace_id: string | null;
        };
        Insert: {
          id?: string;
          type: string;
          payload?: Json;
          run_at: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          claimed_at?: string | null;
          dedupe_key?: string | null;
          workspace_id?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          payload?: Json;
          run_at?: string;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          claimed_at?: string | null;
          dedupe_key?: string | null;
          workspace_id?: string | null;
        };
      };
      secret_access_events: {
        Row: {
          id: string;
          workspace_id: string;
          secret_id: string | null;
          action: string;
          actor_type: string;
          actor_id: string | null;
          purpose: string | null;
          outcome: string;
          detail: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          secret_id?: string | null;
          action: string;
          actor_type: string;
          actor_id?: string | null;
          purpose?: string | null;
          outcome?: string;
          detail?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          secret_id?: string | null;
          action?: string;
          actor_type?: string;
          actor_id?: string | null;
          purpose?: string | null;
          outcome?: string;
          detail?: Json;
          created_at?: string;
        };
      };
      secret_versions: {
        Row: {
          id: string;
          workspace_id: string;
          secret_id: string;
          version: number;
          algorithm: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          wrapped_dek: string;
          kek_provider: string;
          kek_key_id: string;
          kek_version: number | null;
          created_by: string | null;
          created_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          secret_id: string;
          version: number;
          algorithm?: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          wrapped_dek: string;
          kek_provider: string;
          kek_key_id: string;
          kek_version?: number | null;
          created_by?: string | null;
          created_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          secret_id?: string;
          version?: number;
          algorithm?: string;
          ciphertext?: string;
          iv?: string;
          auth_tag?: string;
          wrapped_dek?: string;
          kek_provider?: string;
          kek_key_id?: string;
          kek_version?: number | null;
          created_by?: string | null;
          created_at?: string;
          revoked_at?: string | null;
        };
      };
      secrets: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          kind: string;
          provider: string | null;
          description: string;
          binding: string | null;
          status: string;
          current_version: number;
          expires_at: string | null;
          last_used_at: string | null;
          last_used_by: string | null;
          rotated_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          revoked_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          kind: string;
          provider?: string | null;
          description?: string;
          binding?: string | null;
          status?: string;
          current_version?: number;
          expires_at?: string | null;
          last_used_at?: string | null;
          last_used_by?: string | null;
          rotated_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          revoked_at?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          kind?: string;
          provider?: string | null;
          description?: string;
          binding?: string | null;
          status?: string;
          current_version?: number;
          expires_at?: string | null;
          last_used_at?: string | null;
          last_used_by?: string | null;
          rotated_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          revoked_at?: string | null;
          deleted_at?: string | null;
        };
      };
      sequence_enrollments: {
        Row: {
          id: string;
          sequence_id: string;
          contact_id: string;
          channel_id: string;
          current_step_index: number;
          status: string;
          enrolled_at: string | null;
          next_step_at: string | null;
          completed_at: string | null;
          current_operation_id: string | null;
          operation_checks: number;
          last_error: string | null;
        };
        Insert: {
          id?: string;
          sequence_id: string;
          contact_id: string;
          channel_id: string;
          current_step_index?: number;
          status?: string;
          enrolled_at?: string | null;
          next_step_at?: string | null;
          completed_at?: string | null;
          current_operation_id?: string | null;
          operation_checks?: number;
          last_error?: string | null;
        };
        Update: {
          id?: string;
          sequence_id?: string;
          contact_id?: string;
          channel_id?: string;
          current_step_index?: number;
          status?: string;
          enrolled_at?: string | null;
          next_step_at?: string | null;
          completed_at?: string | null;
          current_operation_id?: string | null;
          operation_checks?: number;
          last_error?: string | null;
        };
      };
      sequences: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          status: string;
          steps: Json;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          status?: string;
          steps?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          status?: string;
          steps?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      system_heartbeats: {
        Row: {
          component: string;
          last_run_at: string;
          last_ok_at: string | null;
          status: string;
          duration_ms: number | null;
          detail: Json;
        };
        Insert: {
          component: string;
          last_run_at: string;
          last_ok_at?: string | null;
          status: string;
          duration_ms?: number | null;
          detail?: Json;
        };
        Update: {
          component?: string;
          last_run_at?: string;
          last_ok_at?: string | null;
          status?: string;
          duration_ms?: number | null;
          detail?: Json;
        };
      };
      tags: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          color: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          color?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          color?: string | null;
          created_at?: string;
        };
      };
      task_events: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string;
          level: string;
          message: string;
          data: Json;
          actor_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id: string;
          level?: string;
          message: string;
          data?: Json;
          actor_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string;
          level?: string;
          message?: string;
          data?: Json;
          actor_id?: string | null;
          created_at?: string;
        };
      };
      task_schedules: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          kind: string;
          input: Json;
          execution_mode: string;
          cron: string | null;
          interval_seconds: number | null;
          timezone: string;
          campaign_id: string | null;
          enabled: boolean;
          next_run_at: string;
          last_run_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          kind: string;
          input?: Json;
          execution_mode?: string;
          cron?: string | null;
          interval_seconds?: number | null;
          timezone?: string;
          campaign_id?: string | null;
          enabled?: boolean;
          next_run_at: string;
          last_run_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          kind?: string;
          input?: Json;
          execution_mode?: string;
          cron?: string | null;
          interval_seconds?: number | null;
          timezone?: string;
          campaign_id?: string | null;
          enabled?: boolean;
          next_run_at?: string;
          last_run_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          campaign_id: string | null;
          kind: string;
          objective: string;
          state: string;
          current_step: string | null;
          depends_on: string[];
          execution_mode: string;
          retry_policy: Json;
          attempts: number;
          next_run_at: string;
          lease_owner: string | null;
          lease_expires_at: string | null;
          idempotency_key: string;
          input: Json;
          result: Json | null;
          error: Json | null;
          requires_approval: boolean;
          approval_state: string;
          approved_by: string | null;
          approved_at: string | null;
          human_intervention: string;
          intervention_reason: string | null;
          schedule_id: string | null;
          correlation_id: string;
          subject_type: string | null;
          subject_id: string | null;
          priority: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          started_at: string | null;
          finished_at: string | null;
          dead_lettered_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          campaign_id?: string | null;
          kind: string;
          objective: string;
          state?: string;
          current_step?: string | null;
          depends_on?: string[];
          execution_mode?: string;
          retry_policy?: Json;
          attempts?: number;
          next_run_at?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          idempotency_key: string;
          input?: Json;
          result?: Json | null;
          error?: Json | null;
          requires_approval?: boolean;
          approval_state?: string;
          approved_by?: string | null;
          approved_at?: string | null;
          human_intervention?: string;
          intervention_reason?: string | null;
          schedule_id?: string | null;
          correlation_id?: string;
          subject_type?: string | null;
          subject_id?: string | null;
          priority?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          dead_lettered_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          campaign_id?: string | null;
          kind?: string;
          objective?: string;
          state?: string;
          current_step?: string | null;
          depends_on?: string[];
          execution_mode?: string;
          retry_policy?: Json;
          attempts?: number;
          next_run_at?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          idempotency_key?: string;
          input?: Json;
          result?: Json | null;
          error?: Json | null;
          requires_approval?: boolean;
          approval_state?: string;
          approved_by?: string | null;
          approved_at?: string | null;
          human_intervention?: string;
          intervention_reason?: string | null;
          schedule_id?: string | null;
          correlation_id?: string;
          subject_type?: string | null;
          subject_id?: string | null;
          priority?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          dead_lettered_at?: string | null;
        };
      };
      triggers: {
        Row: {
          id: string;
          flow_id: string;
          channel_id: string | null;
          type: string;
          config: Json;
          priority: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          flow_id: string;
          channel_id?: string | null;
          type: string;
          config?: Json;
          priority?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          flow_id?: string;
          channel_id?: string | null;
          type?: string;
          config?: Json;
          priority?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      webhook_events: {
        Row: {
          event_id: string;
          received_at: string;
          source: string;
          delivery_id: string | null;
          event_type: string | null;
          status: string;
          attempt_count: number;
          claimed_at: string;
          completed_at: string | null;
          last_error: string | null;
        };
        Insert: {
          event_id: string;
          received_at?: string;
          source?: string;
          delivery_id?: string | null;
          event_type?: string | null;
          status?: string;
          attempt_count?: number;
          claimed_at?: string;
          completed_at?: string | null;
          last_error?: string | null;
        };
        Update: {
          event_id?: string;
          received_at?: string;
          source?: string;
          delivery_id?: string | null;
          event_type?: string | null;
          status?: string;
          attempt_count?: number;
          claimed_at?: string;
          completed_at?: string | null;
          last_error?: string | null;
        };
      };
      work_items: {
        Row: {
          id: string;
          workspace_id: string;
          reference: number;
          name: string;
          description: string;
          kind: string;
          status: string;
          priority: string;
          queue_id: string | null;
          assignee_id: string | null;
          contact_id: string | null;
          company_id: string | null;
          conversation_id: string | null;
          due_at: string | null;
          first_response_minutes: number;
          resolution_minutes: number;
          warning_fraction: number;
          first_responded_at: string | null;
          resolved_at: string | null;
          escalated: boolean;
          escalation_reason: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          reference?: number;
          name: string;
          description?: string;
          kind?: string;
          status?: string;
          priority?: string;
          queue_id?: string | null;
          assignee_id?: string | null;
          contact_id?: string | null;
          company_id?: string | null;
          conversation_id?: string | null;
          due_at?: string | null;
          first_response_minutes?: number;
          resolution_minutes?: number;
          warning_fraction?: number;
          first_responded_at?: string | null;
          resolved_at?: string | null;
          escalated?: boolean;
          escalation_reason?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          reference?: number;
          name?: string;
          description?: string;
          kind?: string;
          status?: string;
          priority?: string;
          queue_id?: string | null;
          assignee_id?: string | null;
          contact_id?: string | null;
          company_id?: string | null;
          conversation_id?: string | null;
          due_at?: string | null;
          first_response_minutes?: number;
          resolution_minutes?: number;
          warning_fraction?: number;
          first_responded_at?: string | null;
          resolved_at?: string | null;
          escalated?: boolean;
          escalation_reason?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      work_queues: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      worker_identities: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          token_hash: string;
          token_prefix: string;
          modes: string[];
          max_concurrency: number;
          created_by: string | null;
          created_at: string;
          last_seen_at: string | null;
          revoked_at: string | null;
          capabilities: Json;
          version: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          token_hash: string;
          token_prefix: string;
          modes?: string[];
          max_concurrency?: number;
          created_by?: string | null;
          created_at?: string;
          last_seen_at?: string | null;
          revoked_at?: string | null;
          capabilities?: Json;
          version?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          token_hash?: string;
          token_prefix?: string;
          modes?: string[];
          max_concurrency?: number;
          created_by?: string | null;
          created_at?: string;
          last_seen_at?: string | null;
          revoked_at?: string | null;
          capabilities?: Json;
          version?: string | null;
        };
      };
      workspace_invites: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: string;
          invited_by: string;
          status: string;
          created_at: string | null;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: string;
          invited_by: string;
          status?: string;
          created_at?: string | null;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: string;
          invited_by?: string;
          status?: string;
          created_at?: string | null;
          expires_at?: string | null;
        };
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          late_api_key_encrypted: string | null;
          global_keywords: Json | null;
          created_at: string;
          updated_at: string;
          ai_api_key: string | null;
          ai_provider: string;
          webhook_secret: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          late_api_key_encrypted?: string | null;
          global_keywords?: Json | null;
          created_at?: string;
          updated_at?: string;
          ai_api_key?: string | null;
          ai_provider?: string;
          webhook_secret?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          late_api_key_encrypted?: string | null;
          global_keywords?: Json | null;
          created_at?: string;
          updated_at?: string;
          ai_api_key?: string | null;
          ai_provider?: string;
          webhook_secret?: string | null;
        };
      };
    };
    Views: {
    };
    Functions: {
      apply_social_gateway_inbound_conversation: { Args: { p_conversation_id: string; p_occurred_at: string; p_preview: string; p_gateway_conversation_id: string }; Returns: undefined };
      approve_task: { Args: { p_task: string; p_approve: boolean; p_note?: string }; Returns: string };
      bulk_update_work_items: { Args: { p_workspace_id: string; p_changes: Json }; Returns: number };
      campaign_engagement: { Args: { p_workspace: string; p_since?: string }; Returns: { campaign_id: string; comments: number; commenters: number; touchpoints: number; contacts: number; first_touch_contacts: number }[] };
      cancel_task: { Args: { p_task: string; p_reason?: string }; Returns: string };
      claim_social_gateway_webhook: { Args: { p_event_id: string; p_delivery_id: string; p_event_type: string; p_channel_id: string; p_envelope: Json }; Returns: string };
      claim_tasks: { Args: { p_worker: string; p_modes: string[]; p_limit: number; p_lease_seconds: number; p_workspace_id?: string; p_max_running?: number }; Returns: Json[] };
      complete_task: { Args: { p_task: string; p_worker: string; p_result?: Json }; Returns: boolean };
      confirm_manual_publication: { Args: { p_variant: string; p_external_url: string; p_external_ref?: string }; Returns: string };
      defer_task: { Args: { p_task: string; p_worker: string; p_next_run_at: string; p_step?: string }; Returns: boolean };
      fail_task: { Args: { p_task: string; p_worker: string; p_error: Json; p_decision: string; p_next_run_at?: string }; Returns: string };
      heartbeat_task: { Args: { p_task: string; p_worker: string; p_lease_seconds: number }; Returns: boolean };
      increment_broadcast_failed: { Args: { b_id: string }; Returns: undefined };
      increment_broadcast_sent: { Args: { b_id: string }; Returns: undefined };
      increment_unread: { Args: { conv_id: string; preview: string }; Returns: undefined };
      is_workspace_member: { Args: { ws_id: string }; Returns: boolean };
      is_workspace_owner: { Args: { ws_id: string }; Returns: boolean };
      legacy_queue_status: { Args: Record<PropertyKey, never>; Returns: { job_type: string; target: string; pending: number; processing: number; failed_7d: number; oldest_pending: string }[] };
      legacy_queue_target: { Args: { p_job_type: string }; Returns: string };
      legacy_task_retry_policy: { Args: Record<PropertyKey, never>; Returns: Json };
      materialize_schedule: { Args: { p_schedule: string; p_expected: string; p_following: string }; Returns: string };
      operator_metrics: { Args: { p_workspace_id: string }; Returns: Json };
      record_heartbeat: { Args: { p_component: string; p_status: string; p_duration_ms: number; p_detail: Json }; Returns: undefined };
      recover_expired_leases: { Args: Record<PropertyKey, never>; Returns: number };
      refresh_sla_notifications: { Args: { p_as_of?: string }; Returns: number };
      resolve_publication: { Args: { p_variant: string; p_outcome: string; p_external_url?: string; p_external_ref?: string }; Returns: string };
      retry_task: { Args: { p_task: string; p_note?: string }; Returns: string };
      schedule_broadcast_delivery: { Args: { p_broadcast_id: string }; Returns: number };
      schedule_content_item: { Args: { p_draft: string; p_at: string; p_plan: Json }; Returns: number };
      schedule_flow_resume: { Args: { p_payload: Json; p_run_at: string }; Returns: string };
      task_log: { Args: { p_workspace: string; p_task: string; p_level: string; p_message: string; p_data?: Json }; Returns: undefined };
      unschedule_content_item: { Args: { p_draft: string; p_variant?: string }; Returns: number };
      uuid_generate_v4: { Args: Record<PropertyKey, never>; Returns: string };
      workspace_operator_directory: { Args: { p_workspace_id: string }; Returns: { user_id: string; display_name: string; role: string }[] };
    };
    Enums: {
    };
  };
};

export type GeneratedTables = GeneratedDatabase["public"]["Tables"];
export type GeneratedRow<T extends keyof GeneratedTables> = GeneratedTables[T]["Row"];
